apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app.kubernetes.io/name: spring-petclinic-steve1
  name: spring-petclinic-steve1-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: spring-petclinic-steve1
  template:
    metadata:
      labels:
        app.kubernetes.io/name: spring-petclinic-steve1
        app.kubernetes.io/part-of: spring-petclinic-steve1
        tanzu.app.live.view: "true"
        tanzu.app.live.view.application.name: spring-petclinic-steve1
    spec:
      containers:
      - image: spring-petclinic-steve1:2.4.2
        imagePullPolicy: IfNotPresent
        livenessProbe:
          httpGet:
            path: /actuator/health/liveness
            port: 8080
          initialDelaySeconds: 15
        name: app
        ports:
        - containerPort: 8080
        readinessProbe:
          httpGet:
            path: /actuator/health/readiness
            port: 8080
          initialDelaySeconds: 15